import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/Navbar'
import { ModalProvider } from '@/components/providers/modal-provider'
import { ConvexClientProvider } from '@/components/providers/convex-provider'

const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '500', '300', '400', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'Kurashiku',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <ClerkProvider>
    <ConvexClientProvider>

      <html lang="en">
        <body className={poppins.className}>
          <ModalProvider />
          <Navbar />
          <div className='mt-16'>
            {children}
          </div>
        </body>
      </html>
    </ConvexClientProvider>
    // </ClerkProvider>
  )
}
